# test233
FROM node:18-alpine AS base

RUN apk add --no-cache libc6-compat

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* .npmrc* ./

RUN pnpm fetch

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN pnpm install --force
